repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        args: ["--autofix", "--indent", "2"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.2"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
     - id: codespell
